#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="${ENV_FILE:-pilot-runtime/.env}"
COMPOSE=(docker compose --env-file "$ENV_FILE" -f pilot-runtime/docker-compose.yml)

banner "Nightingale local Pilot Postgres"

stage "Confirm Docker Desktop"
step "Keep Docker Desktop open until its status says Engine running."
if docker version >/dev/null 2>&1; then
  say "Docker Engine is ready."
else
  warn "Docker is not ready yet. Open Docker Desktop and wait for Engine running."
  pause "Press Enter after Docker is running, then re-run this wizard."
  exit 1
fi

stage "Create local-only database credentials"
say "These values are written only to $ENV_FILE, which is ignored by Git."
say "Use 16+ characters: letters, digits, hyphens, and underscores only."
ask_secret PILOT_ADMIN_DB_PASSWORD "Choose a local admin database password:"
ask_secret PILOT_WEB_DB_PASSWORD "Choose a different local web-role password:"
if [[ -z "$PILOT_ADMIN_DB_PASSWORD" || -z "$PILOT_WEB_DB_PASSWORD" ]]; then
  warn "Both passwords are required. Nothing was started."
  exit 1
fi
if [[ ! "$PILOT_ADMIN_DB_PASSWORD" =~ ^[A-Za-z0-9_-]{16,}$ || ! "$PILOT_WEB_DB_PASSWORD" =~ ^[A-Za-z0-9_-]{16,}$ ]]; then
  warn "Passwords must be 16+ characters and use only letters, digits, hyphens, or underscores."
  exit 1
fi
if [[ "$PILOT_ADMIN_DB_PASSWORD" == "$PILOT_WEB_DB_PASSWORD" ]]; then
  warn "Use two different passwords so the restricted web role is separately protected."
  exit 1
fi
write_env PILOT_ADMIN_DB_PASSWORD "$PILOT_ADMIN_DB_PASSWORD"
write_env PILOT_WEB_DB_PASSWORD "$PILOT_WEB_DB_PASSWORD"
write_env PILOT_ADMIN_DATABASE_URL "postgresql://nightingale:${PILOT_ADMIN_DB_PASSWORD}@localhost:5434/nightingale_pilot"
write_env PILOT_DATABASE_URL "postgresql://nightingale_web:${PILOT_WEB_DB_PASSWORD}@localhost:5434/nightingale_pilot"

stage "Start the isolated Postgres container"
step "Docker will download postgres:16-alpine the first time, then start the project database on port 5434."
"${COMPOSE[@]}" up -d
"${COMPOSE[@]}" exec -T postgres pg_isready -U nightingale -d nightingale_pilot
say "Postgres is accepting local connections."

stage "Create restricted roles and apply the Foundation migration"
step "The administrator creates the owner, web, and worker roles; the wizard then sets the web password without printing it."
"${COMPOSE[@]}" exec -T postgres psql -v ON_ERROR_STOP=1 -U nightingale -d nightingale_pilot < pilot-runtime/db/migrations/0000_security_roles.sql
printf "ALTER ROLE nightingale_web PASSWORD '%s';\n" "$PILOT_WEB_DB_PASSWORD" | "${COMPOSE[@]}" exec -T postgres psql -v ON_ERROR_STOP=1 -U nightingale -d nightingale_pilot
"${COMPOSE[@]}" exec -T postgres psql -v ON_ERROR_STOP=1 -U nightingale -d nightingale_pilot < pilot-runtime/db/migrations/0001_foundation.sql

stage "Verify the Foundation boundary"
"${COMPOSE[@]}" exec -T postgres psql -U nightingale -d nightingale_pilot -c "SELECT rolname, rolbypassrls FROM pg_roles WHERE rolname IN ('nightingale_web', 'nightingale_worker') ORDER BY rolname;"
say "Expected result: both roles show rolbypassrls = f."
say "Your local Postgres instance is ready for the Pilot Foundation tests."

finish
